// usar extension en vscode Rest Client
GET http://localhost:1234/pokemon/ditto
###para crear un pokemon

POST http://localhost:1234/pokemon
Content-Type: application/json

{
  "name": "Pikachu",
  "type": "Electric"
}